spring.application.name=CORE_PMS_API

#spring.datasource.url=jdbc:mysql://159.223.42.61:3306
#spring.datasource.username=pms_core
#spring.datasource.password=ojeaINVg6TdYhHo8j
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
##
#
#spring.datasource.url=jdbc:mysql://159.223.42.61:3306/pms?serverTimezone=Asia/Baku
#spring.datasource.username=pms
#spring.datasource.password=Dv-9%50VyhtbuSx%V
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8085
#doxuzmin doxuzüz doxsan do?xxuz

camera.dido-uri=http://%s/cgi-bin/dido/setdo.cgi
camera.dido-username=admin
camera.dido-password=admin

camera.vivotek.username=admin
camera.vivotek.password=Axsis.2020

panel.uri=http://%s/5?text=%s
panel.speed=5
panel.delay=2000

log.path=/opt/turpark_core/log
